### ISSUE TITLE
postconf_master is only parsed on a Puppet run *following* Postfix install

### ISSUE THREAD

**Issue by craigwatson** [oxc/puppet-postfix#9]
On an initial Puppet run (i.e. from a vanilla OS) using `puppet apply` locally (masterless):

```
Error: Could not find a suitable provider for postconf_master
```

On the following Puppet run:
```
Notice: /Stage[main]/Custom::Profile::Clamav/Postconf_master[amavis/unix]/ensure: created
Notice: /Stage[main]/Custom::Profile::Clamav/Postconf_master[127.0.0.1:10025/inet]/ensure: created
```

**Comment by oxc** [comment]
I'm not sure if there is a good way to fix this. Any ideas?

**Comment by craigwatson** [comment]
It seems like the problem is due to the `confine` in the `postconf_master` provider.

On first-run, Postfix is not installed, and as facts are parsed before the Puppet run, the provider fails to initialise.

The only way around this is to remove the confine:

```
confine postfixversion: '2.11'
```
